### ISSUE TITLE
Preview error

### ISSUE THREAD

**Issue by barryjenkin** [danielstorey/adapt-blinds#6]
Hi there.
Love this component but am lately getting an error when trying to preview in a course using the latest authoring tool. I created a new test course with Vanilla theme / Box menu and still getting the error. In my previous instance of the tool it's running fine. Any clues as to what this might be?

**Comment by danielstorey** [comment]
Hi Barry, I'm glad you like the component and sorry that you seem to be experiencing issues. I'm going to need a little more information to be able to help you further though.

Does preview only fail to work when this component is used? Ie have you tried removing it and previewing? Also, are you getting any errors in the browser console. F12 on PC, ⌘⌥I on Mac, in most browsers. If there is an error then enabling source maps in your course config will help pinpoint it a bit better. Please send a screenshot if you do get any errors.

Thanks and hope I can help in some way

**Comment by barryjenkin** [comment]
Hey Daniel. Yes it's only when the component is added to the course; when removed the course previews fine. I got these 2 errors in my console if that helps.

![screen shot 2018-02-26 at 9 16 56 am](https://user-images.githubusercontent.com/24560844/36647188-f1b68aac-1ad5-11e8-9f90-92f774d52ced.png)

**Comment by avojay** [comment]
Hi Daniel, I'm in the same boat as @barryjenkin here. Not able to preview once adding in the component to my course. These are the console log errors I'm getting at the moment: 

<img width="771" alt="screen shot 2018-03-13 at 15 41 26" src="https://user-images.githubusercontent.com/35927747/37352533-5987f43a-26d5-11e8-98d2-999cc3943977.png">

Course previews fine with no errors if component removed. Any ideas?

**Comment by reddprime** [comment]
Hi Daniel, 

Just tried out the component, I am getting the same error when trying to preview. 

Error log:

3s3.amazonaws.com/jscache/175abcd073ccafc00c.js Failed to load resource: the server responded with a status of 403 (Blocked by ESET Security)
:5000/build/js/ace/mode-less.js Failed to load resource: the server responded with a status of 404 (Not Found)
:5000/#editor/5ab3619ec5f4838e0264b07e/settings:1 Refused to execute script from 'http://10.30.100.26:5000/build/js/ace/mode-less.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
:5000/build/js/ace/theme-chrome.js Failed to load resource: the server responded with a status of 404 (Not Found)
:5000/#editor/5ab3619ec5f4838e0264b07e/settings:1 Refused to execute script from 'http://10.30.100.26:5000/build/js/ace/theme-chrome.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
5s3.amazonaws.com/jscache/175abcd073ccafc00c.js Failed to load resource: the server responded with a status of 403 (Blocked by ESET Security)
:5000/api/content/component/5ab4ab37e412cfd402bd12d3 Failed to load resource: the server responded with a status of 404 (Not Found)
11s3.amazonaws.com/jscache/175abcd073ccafc00c.js Failed to load resource: the server responded with a status of 403 (Blocked by ESET Security)
Grammarly.js:33084 Uncaught TypeError: Cannot read property 'querySelector' of null
    at Object.exit [as remove] (Grammarly.js:33084)
    at editorRemove (Grammarly.js:21991)
    at Object.remove (Grammarly.js:21791)
    at Array.remove (Grammarly.js:32431)
    at Object.emit (Grammarly.js:10164)
    at remove (Grammarly.js:32637)
    at Array.forEach (<anonymous>)
    at MutationObserver.onMutation (Grammarly.js:32622)
7s3.amazonaws.com/jscache/175abcd073ccafc00c.js Failed to load resource: the server responded with a status of 403 (Blocked by ESET Security)

**Comment by SteveX** [comment]
On authoring 0.5.0 I get these errors on preview when Blinds is in use:
TypeError: children[i].getAncestorModels is not a function. (In 'children[i].getAncestorModels()', 'children[i].getAncestorModels' is undefined)
TypeError: undefined is not an object (evaluating 'child.setOnChildren.apply')

If I delete the Blinds component from the page the preview loads fine without errors.

**Comment by qverent** [comment]
Hello there! I am getting the same issues as everyone else.

On a side note: I am really enjoying all the custom components you made. Thank you for contributing to the Adapt community!

**Comment by elearningdifferently** [comment]
I was able to solve the issue by editing adapt-blinds.js file in js folder. 
changing line 3 ` "core/js/models/itemModel",` to `"core/js/models/itemsModel",`

This fixes it for me... it might be that Adapt Authoring tool uses not the latest version of Adapt Framework. 

@danielstorey thank you for an amazing component!

**Comment by o0larrylurex0o** [comment]
Hello, I have the same problem, but the solution didn't work I just restarted the server and still have have the same problem... I'm kinda new to Adapt ^^
Do I need to do something else ? thx @elearningdifferently

**Comment by danielstorey** [comment]
So sorry that it's taken me so long to get round to this! There seems to be a few slightly different things going on here. Have you tried updating your framework versions?

**Comment by qverent** [comment]
No problem! 

I did eventually switch over to using the Framework instead of the Authoring Too but when I tried to install, the CLI said that this plugin wasn't compatible. As a newbie, that message scared me off so I didn't go further and can't report on the results of that. 

But thank you again for taking the time to make these great plugins for the Adapt community :)
